##### FeatureInitializer Config

# default: "", prefix for redis key
redisKeyPrefix: 2tower_

# default: null, one of initialUserDataPath or initialItemDataPath must be
# provided. Only support parquet file
initialItemDataPath: /opt/work/similarity/item_ebd.parquet

# default: null, if loadInitialData=true and initialItemDataPath != null, itemIDColumn and
# itemFeatureColumns must be provided
itemIDColumn: tweet_id
itemFeatureColumns: prediction

### Redis Configuration
# Default: 8085, which port to create the server
servicePort: 8085

# Default: null, open a port for prometheus monitoring tool, if set, user can check the
# performance using prometheus
monitorPort: 1236
